# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
before_install:
      # Install GMT trunk
      - pwd
      - sudo apt-get install subversion build-essential cmake libcurl4-gnutls-dev libnetcdf-dev libgdal1-dev libfftw3-dev libpcre3-dev liblapack-dev ghostscript
      #- svn checkout svn://gmtserver.soest.hawaii.edu/gmt5/branches/5.4 $HOME/gmt
      - git clone https://github.com/GenericMappingTools/gmt.git $HOME/gmt
      - PATH="$HOME/gmt/bin:$PATH"
      - export PATH
      - echo 'export PATH="$HOME/gmt/bin:$PATH"' >>~/.bash_profile
      - cd $HOME/gmt
      #- wget ftp://ftp.soest.hawaii.edu/gshhg/gshhg-gmt-2.3.7.tar.gz
      - wget http://w3.ualg.pt/~jluis/ftp/gshhg-gmt-2.3.7.tar.gz
      #- wget https://mirrors.ustc.edu.cn/gmt/gshhg-gmt-2.3.7.tar.gz
      - tar -xvzf gshhg-gmt-2.3.7.tar.gz
      - wget http://w3.ualg.pt/~jluis/ftp/dcw-gmt-1.1.4.tar.gz
      #- wget https://mirrors.ustc.edu.cn/gmt/dcw-gmt-1.1.4.tar.gz
      - tar -xvzf dcw-gmt-1.1.4.tar.gz
      - mkdir build
      - cd build
      - cmake --config Release .. -DSUPPORT_EXEC_IN_BINARY_DIR=TRUE -DGMT_OPENMP=ON -DCMAKE_INSTALL_PREFIX=$HOME/gmt -DGSHHG_ROOT=$HOME/gmt/gshhg-gmt-2.3.7
      - make -j && make install
      - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/gmt/lib"

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
