# control PostScript files generated by GMT.jl
###################################################
"""
Rename /tmp/GMTtmp.ps to another name
"""
function moveps(outps::String)
    if !occursin("/",outps)
        outeps="./"*outps
    end
    tmpps = GMT.fname_out(Dict())[1]
    run(`mv $tmpps $outps`)
    return nothing
end
###################################################

###################################################
"""
Convert /tmp/GMTtmp.ps to eps file
"""
function saveaseps(outeps::String)
    if !occursin("/",outeps)
        outeps="./"*outeps
    end
    tmpps = GMT.fname_out(Dict())[1]
    run(`ps2eps -f -q $tmpps`)
    tmpeps= replace(tmpps, r"\.ps$" => ".eps")
    run(`mv $tmpeps $outeps`)
    return nothing
end
###################################################

###################################################
"""
Convert /tmp/GMTtmp.ps to png file
"""
function saveaspng(outpng::String; dpi=400::Int64)
    tmpps = GMT.fname_out(Dict())[1]
    run(`ps2eps -f -q $tmpps`)
    tmpeps= replace(tmpps, r"\.ps$" => ".eps")
    run(`convert -density $dpi $tmpeps $outpng`)
    return nothing
end
###################################################

###################################################
"""
Convert ps files to eps files
"""
function ps2eps_series(nstep::Int64; outinfo::Claw.OutputSpec=Claw.OutputSpec())
    # prefix
    prefix=joinpath(outinfo.figdir,outinfo.prefix)
    # each step
    for i = 1:nstep
        # filename
        filename = prefix*@sprintf("%03d",(i-1)+outinfo.start_number)*".ps"
        # check
        if !isfile(filename); println("Not found: $filename"); continue; end;
        # convert
        run(`ps2eps -f -q $filename`)
    end
    # remove .ps file
    figdir=outinfo.figdir
    prefix=outinfo.prefix
    flist = joinpath.(figdir,filter(x->occursin(prefix,x), readdir(figdir)))
    rm.(filter(x->occursin(".ps",x), flist))
    # return
    return nothing
end
###################################################

###################################################
"""
Convert eps files to ong file
"""
function eps2png_series(nstep::Int64; outinfo::Claw.OutputSpec=Claw.OutputSpec(),
                        reserve=false::Bool)
    # prefix
    prefix=joinpath(outinfo.figdir,outinfo.prefix)
    dpi = outinfo.dpi
    # each step
    for i = 1:nstep
        # filename
        filename = prefix*@sprintf("%03d",i-1+outinfo.start_number)*".eps"
        pngname = replace(filename, r"\.eps" => ".png")
        # check
        if !isfile(filename); println("Not found: $filename"); continue; end;
        # convert
        run(`convert -density $dpi $filename $pngname`)
    end
    # remove .eps file if true
    if !reserve;
        figdir=outinfo.figdir
        prefix=outinfo.prefix
        flist = joinpath.(figdir,filter(x->occursin(prefix,x), readdir(figdir)))
        rm.(filter(x->occursin(".eps",x), flist))
    end
    # return
    return nothing
end
###################################################

###################################################
"""
Make .gif animation from png
"""
function makegif(outinfo::Claw.OutputSpec)
    # prefix
    prefix = joinpath(outinfo.figdir,outinfo.prefix)
    fps = outinfo.fps
    filet0 = prefix*@sprintf("%03d",outinfo.start_number)*".png"
    # check
    if !isfile(filet0);
        println("Initial step $filet0  was not found");
        return nothing
    end
    # remove if old file exists
    giffile = prefix*".gif"
    if isfile(giffile); rm(giffile); end
    ## make an animation
    run(`ffmpeg -i $prefix%03d.png -vf palettegen palette.png`)
    run(`ffmpeg -y -r $fps -i $prefix%03d.png -i palette.png -filter_complex paletteuse $giffile`)
    rm("palette.png")

    # return
    return nothing
end
###################################################
